name: build

on: [push,pull_request]


jobs:
  build-simple-example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [0.0.4-dev2020.02.22]
    container:
      image: amutake/satysfi:${{ matrix.version }}
    steps:
      - uses: actions/checkout@v1
      - run: |
          export HOME=/root
          eval $(opam env)
          opam update
          opam install satysfi-base
          opam install satysfi-assert-eq
          opam install satysfi-debug-show-value
          satyrographos install
          satysfi test.saty
        working-directory: ./test
